### ISSUE TITLE
Didn't support :via tuples as broadway names

### ISSUE THREAD

**Issue by feng19** [dashbitco/broadway_dashboard#12]
The new version of Broadway is allowed :via tuples as broadway names.

But the code of Dashboard are not support for it current:

https://github.com/dashbitco/broadway_dashboard/blob/5bddceef9bdd5dfab520779682b3b07356ea0a32/lib/broadway_dashboard.ex#L56

I hope this feature will be supported soon, Many thanks.

**Comment by josevalim** [comment]
Not in our plans at the moment but we are glad to accept contributions!
