### ISSUE TITLE
Broadway pipelines tab fails to load

### ISSUE THREAD

**Issue by amacciola** [dashbitco/broadway_dashboard#18]
Current versions i am using:
```
broadway 1.0.3
broadway_dashboard 0.2.2
broadway_kafka 0.3.4
phoenix_live_dashboard 0.6.4
phoenix_live_view 0.17.7
```

router.ex
```
live_dashboard "/dashboard",
        metrics: TelemetrySupervisor,
        additional_pages: [
          broadway: BroadwayDashboard
        ]
    end
```

**Issue:**
Whenever i load up my `/dashboard` i am unable to access the `/dashboard/broadway` tab. It will load for a while and says the Dashboard is not connected.

Only meaningful log i can find

```
iex(cyn@10.50.0.65)1> 17:24:34.953 request_id=0558abf4-4a16-42a1-8232-e47e5a950a18 [info] GET /ingest/dashboard/broadway
iex(cyn@10.50.0.65)1> 17:24:34.970 request_id=0558abf4-4a16-42a1-8232-e47e5a950a18 [info] Sent 200 in 17ms
iex(cyn@10.50.0.65)1> 17:24:35.867 [info] CONNECTED TO Phoenix.LiveView.Socket in 95µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "JXMuGARSIggZMRUFBjNjL3QrcCosUzYQHEK5wgQyKAahTj6BGJ6Oofcx", "vsn" => "2.0.0"}
iex(cyn@10.50.0.65)1> 17:24:35.961 [info] Function passed as a handler with ID {BroadwayDashboard.Telemetry, #PID<0.1495.0>} is local function.
This mean that it is either anonymous function or capture of function without module specified. That may cause performance penalty when calling such handler. For more details see note in `telemetry:attach/4` documentation.
```

![Screen Shot 2022-05-10 at 7 14 20 PM](https://user-images.githubusercontent.com/54288198/167746416-5a2d568e-b5a0-4320-b17a-a65f60698190.png)

**Comment by amacciola** [comment]
Additional info:
i am trying to run this on a 1 node k8s cluster with only 1 pod running for the application that is hosting the /dashboard

**Comment by amacciola** [comment]
@philss i do see this in the console log errors when trying to make the connection

![Screen Shot 2022-05-11 at 1 37 57 PM](https://user-images.githubusercontent.com/54288198/167922098-f7c61fc2-5ee2-4524-9036-79ff2025100d.png)

**Comment by josevalim** [comment]
This is happening because LiveView in your app does not match LiveView in Dashboard. Make sure both are running on latest and you should be good!

**Comment by amacciola** [comment]
> 

@josevalim thanks testing now

**Comment by amacciola** [comment]
@josevalim fixed it! thanks
