### ISSUE TITLE
Q: How to change the topology or pause/resume the producer in realtime

### ISSUE THREAD

**Issue by moniquelive** [dashbitco/broadway_dashboard#19]
Marlus presentation had a dashboard that could pause/start and change the graph topology in realtime.

How's it done? `Broadway.stop` followed by `Broadway.start_link` ?

Thanks!

**Comment by josevalim** [comment]
That’s how it was done but we decided not to add it because it may be harmful in Kafka. And the dashboard doesn’t have destructive actions as it may run in prod. :)
