### ISSUE TITLE
Add support for Phoenix Live Dashboard 0.7.0

### ISSUE THREAD

**Issue by walter** [dashbitco/broadway_dashboard#21]
Replaces #20 PR as changes needed require decisions around support of earlier versions of Elixir, Erlang, etc.

**Comment by philss** [comment]
@walter I think it's fine to drop support for older versions.

**Comment by walter** [comment]
Would you like me to bump up the Elixir version in mix as well? `~1.12` or `~1.14`?

**Comment by josevalim** [comment]
1.12!

**Comment by philss** [comment]
This was released in version `0.3.0`. Thank you once again!
