### ISSUE TITLE
plan to support phoenix_live_dashboard v8 ?

### ISSUE THREAD

**Issue by chanphiromsok** [dashbitco/broadway_dashboard#25]
<img width="1297" alt="Screen Shot 2023-06-23 at 5 13 31 PM" src="https://github.com/dashbitco/broadway_dashboard/assets/65760336/e7d5824c-8841-4e47-bbd7-c38373ce6af1">

**Comment by josevalim** [comment]
A PR is welcome. An initial attempt was made here but I assume there are more bits to tackle: #24

**Comment by philss** [comment]
This issue was resolved in https://github.com/dashbitco/broadway_dashboard/pull/26, and is released in `v0.4`.
Please update :)
