### ISSUE TITLE
Clarification on “Messages since start” metric in the dashboard

### ISSUE THREAD

**Issue by mustela** [dashbitco/broadway_dashboard#35]
Hi, I have a question about the “Messages since start” metric displayed in the Broadway Dashboard under the “All time” period.

Is this metric counting messages since the entire application started or since the BroadwayDashboard.Metrics module itself started (I think it's this one)? I’m asking because it seems that some older messages are not appearing in the dashboard, and I’m wondering if I’m misunderstanding the time frame of this metric.

Thanks in advance for your help!

**Comment by philss** [comment]
@mustela yeah, you are right. This is since the BroadwayDashboard page first mount (kind of when the `BroadwayDashboard.Metrics` starts). Can you send a PR to clarify that?

**Comment by philss** [comment]
Closed by https://github.com/dashbitco/broadway_dashboard/commit/ea86bc6f2eec0da79d931b182b11a49930749f7b
